# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from pyfuzz.evm import evm_pb2 as evm__pb2


class EVMStub(object):
  """Interface exported by the server.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Reset = channel.unary_unary(
        '/evm.EVM/Reset',
        request_serializer=evm__pb2.Status.SerializeToString,
        response_deserializer=evm__pb2.Status.FromString,
        )
    self.GetAccounts = channel.unary_stream(
        '/evm.EVM/GetAccounts',
        request_serializer=evm__pb2.Status.SerializeToString,
        response_deserializer=evm__pb2.Json.FromString,
        )
    self.Compile = channel.unary_unary(
        '/evm.EVM/Compile',
        request_serializer=evm__pb2.Source.SerializeToString,
        response_deserializer=evm__pb2.Json.FromString,
        )
    self.Deploy = channel.unary_stream(
        '/evm.EVM/Deploy',
        request_serializer=evm__pb2.Json.SerializeToString,
        response_deserializer=evm__pb2.Address.FromString,
        )
    self.SendTx = channel.unary_stream(
        '/evm.EVM/SendTx',
        request_serializer=evm__pb2.SendTxData.SerializeToString,
        response_deserializer=evm__pb2.Json.FromString,
        )


class EVMServicer(object):
  """Interface exported by the server.
  """

  def Reset(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccounts(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Compile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Deploy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendTx(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EVMServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Reset': grpc.unary_unary_rpc_method_handler(
          servicer.Reset,
          request_deserializer=evm__pb2.Status.FromString,
          response_serializer=evm__pb2.Status.SerializeToString,
      ),
      'GetAccounts': grpc.unary_stream_rpc_method_handler(
          servicer.GetAccounts,
          request_deserializer=evm__pb2.Status.FromString,
          response_serializer=evm__pb2.Json.SerializeToString,
      ),
      'Compile': grpc.unary_unary_rpc_method_handler(
          servicer.Compile,
          request_deserializer=evm__pb2.Source.FromString,
          response_serializer=evm__pb2.Json.SerializeToString,
      ),
      'Deploy': grpc.unary_stream_rpc_method_handler(
          servicer.Deploy,
          request_deserializer=evm__pb2.Json.FromString,
          response_serializer=evm__pb2.Address.SerializeToString,
      ),
      'SendTx': grpc.unary_stream_rpc_method_handler(
          servicer.SendTx,
          request_deserializer=evm__pb2.SendTxData.FromString,
          response_serializer=evm__pb2.Json.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'evm.EVM', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
